CREATE TABLE foo (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
PRIMARY KEY (id))
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE foo_extra (
id INT(11) NOT NULL,
extra_info VARCHAR(40) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES foo (id) ON DELETE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE types (
id INT(11) NOT NULL AUTO_INCREMENT,
string VARCHAR(40) NOT NULL,
dateval DATETIME NOT NULL,
boolval TINYINT(1) NOT NULL,
null_ok VARCHAR(20) NULL,
PRIMARY KEY (id))
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE bar (
id INT(11) NOT NULL AUTO_INCREMENT,
foo_id INT(11), 
name VARCHAR(40) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (foo_id) REFERENCES foo (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE category (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE category_map (
category_id INT(11),
foo_id INT(11),
FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
FOREIGN KEY (foo_id) REFERENCES foo (id) ON DELETE CASCADE,
PRIMARY KEY (category_id, foo_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE category_map_with_dups (
category_id INT(11),
foo_id INT(11),
other_column INT(11),
FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
FOREIGN KEY (foo_id) REFERENCES foo (id) ON DELETE CASCADE,
PRIMARY KEY (category_id, foo_id, other_column)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
