ALTER TABLE cg_channel MODIFY COLUMN name VARCHAR(255) NOT NULL;
ALTER TABLE cg_channel MODIFY COLUMN url VARCHAR(255) NOT NULL;
ALTER TABLE cg_channel MODIFY COLUMN website_url VARCHAR(255) NOT NULL;
ALTER TABLE cg_channel MODIFY COLUMN publisher VARCHAR(255) NOT NULL;

ALTER TABLE cg_channel_item MODIFY COLUMN url VARCHAR(255) NOT NULL;
ALTER TABLE cg_channel_item MODIFY COLUMN name VARCHAR(255) NOT NULL;
